### ISSUE TITLE
Lots of "LazyCompile: .."

### ISSUE THREAD

**Issue by phillipj** [thlorenz/flamegraph#10]
Hi Thorsten,

I'm getting alot of LazyCompile prefixes in my flamegraphs. Using Instruments to generate callgraphs and mapfiles + node v0.11.15 built from source.

Pretty sure I didnt see any of LazyCompiles in january... Am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/1231635/6751607/1bff13a2-cf06-11e4-931a-2185d7c01139.png)

**Comment by thlorenz** [comment]
Ah shoot they aren't getting filtered properly.

Could you try to use [cpuprofilify](https://github.com/thlorenz/cpuprofilify) and see if you get the same?
I want to see if this is just Instruments related.

**Comment by phillipj** [comment]
Sure! I'll give it a shot and come back to you

**Comment by thlorenz** [comment]
Also in the meantime you can checkout tag 0.4 or 0.5 and run the site locally. 
Just run [`npm run bundle`](https://github.com/thlorenz/flamegraph/blob/gh-pages/package.json#L26) followed by `open web/index.html` to do so.

**Comment by phillipj** [comment]
This was an cpuprofilify issue as you thought, PR opened.

**Comment by thlorenz** [comment]
Thanks @phillipj will have a look.
