### ISSUE TITLE
turn chrome .cpuprofile into flamegraph array/lines

### ISSUE THREAD

**Issue by linus-amg** [thlorenz/flamegraph#14]
hi,

i would like to know if there is a way to use a .cpuprofile json from chrome to create a flamegraph?

**Comment by linus-amg** [comment]
example:
https://www.dropbox.com/s/2w27813bxa679gm/CPU-20151028T132333.cpuprofile?dl=0

**Comment by linus-amg** [comment]
i will try this https://www.npmjs.com/package/chrome2calltree

**Comment by taxilian** [comment]
This already works; from the command line just pass in `-inputtype cpuprofile` or from the API pass in `{inputtype: 'cpuprofile'}`

**Comment by linus-amg** [comment]
thanks

**Comment by linus-amg** [comment]
hi, im trying to use the API with a chrome cpu profile and get the following error:

```
TypeError: First arg needs to be an array of lines.
```

the first argument (Array, <string>) is indeed an object so thats whats wrong

``` js
{ typeId: 'CPU',
  uid: 1,
  title: 'Profile 1',
  head: 
   { functionName: '(root)',
     url: '',
     lineNumber: 0,
     callUID: 44,
     bailoutReason: '',
     id: 1,
     scriptId: 0,
     hitCount: 0,
     children: [ [Object], [Object], [Object], [Object] ] },
  startTime: 54602,
  endTime: 54602,
  samples: [ 32, 33, 34, 46, 47, 48 ],
  timestamps: 
   [ 54602942361,
     54602943491,
     54602944649,
     54602945684,
     54602946756,
     54602947827 ] }
```

but i dont know how to get the array of lines from that object, what should i do to make it work?

**Comment by linus-amg** [comment]
i pass in the whole cpu profile directly and removed the array check and everything works as expected
