### ISSUE TITLE
Error in the online app

### ISSUE THREAD

**Issue by baldurh** [thlorenz/flamegraph#16]
When I try using the online app I get `Cannot read property 'width' of undefined`
It is a csv file generated by Apple Instruments. And it fails with or without the `.map` file.

See here:
![screen shot 2016-02-26 at 14 36 18](https://cloud.githubusercontent.com/assets/1823617/13355041/513182d2-dc96-11e5-8bae-62c6b5841698.png)

**Comment by cmdcolin** [comment]
I get this error too, in Chrome specifically (with a cpuprofile file)

I tested it in Safari 9.0.3, and it worked fine though

**Comment by thlorenz** [comment]
Should've been fixed now could you try again?
