### ISSUE TITLE
Flamegraphs generated with OSX instruments data are incorrect

### ISSUE THREAD

**Issue by bjouhier** [thlorenz/flamegraph#17]
Flamegraphs generated from instruments CSV files are wrong. For example, with the following CSV file

```
Running Time,Self,,Symbol Name
100.0ms   100%,0, , foo
50.0ms   50%,0, ,  bar
50.0ms   50%,10, ,   baz
40.0ms   40%,40, ,    zoo
50.0ms   50%,50, ,  qux
```

I get:
<img width="404" alt="capture d ecran 2016-02-28 a 22 45 36" src="https://cloud.githubusercontent.com/assets/415044/13382136/2d50f504-de6d-11e5-82a7-b24e81eff940.png">
instead of:
<img width="401" alt="capture d ecran 2016-02-28 a 22 46 02" src="https://cloud.githubusercontent.com/assets/415044/13382138/3bbb306e-de6d-11e5-825a-1419897bcbed.png">

**Comment by bjouhier** [comment]
@thlorenz The problem comes from the conversion algorithm in cpuprofilify. I fixed it over there but it needs to be pushed to NPM so that flamegraph picks it up. Would be nice to update the [online tool](http://thlorenz.com/flamegraph/web/) too.

**Comment by thlorenz** [comment]
Sorry, stopped supporting Instruments callgraphs, soo much easier generated with dtrace directly.
More info [here](https://github.com/thlorenz/cpuprofilify#example).
