### ISSUE TITLE
"No input type given and unable to detect it for the given input"

### ISSUE THREAD

**Issue by retrohacker** [thlorenz/flamegraph#2]
![coreos2st](https://cloud.githubusercontent.com/assets/1081565/5160626/ff5822b2-7356-11e4-9aa2-71bf25946c7a.png)

I'm probably doing something obviously wrong here, but it doesn't seem my perf.data file is correct... Using perf version 3.16.0 on Debian Jessie. Node version is v0.11.14 installed with nvm.

**Comment by thlorenz** [comment]
Looks like you are on Linux, you can just run `perf script` and load the result into the app. No need to load the map file (see instructions on the app page).

Make sure to load the result of `perf script` as the first file _instead_ of the map file.

**Comment by retrohacker** [comment]
Thanks :heart:
