### ISSUE TITLE
[enhancement] clicking on a bar in the svg should zoom that section

### ISSUE THREAD

**Issue by rafiquemt** [thlorenz/flamegraph#6]
in the perl generated flamegraph (from brendan gregg), you can zoom into a subsection when you click on a bar in the svg
would be nice to have in the svg generated with your tool

**Comment by thlorenz** [comment]
Interesting, could you provide screenshots please so I get an idea of how that works?
I basically ported these from @brendangregg's scripts, so he must have added this feature recently.

**Comment by rafiquemt** [comment]
![zoom](https://cloud.githubusercontent.com/assets/1588251/5732418/463725fe-9b46-11e4-96ae-407f1471df55.gif)
sorry for the 8mb gif, but quickest way to attach a video

**Comment by thlorenz** [comment]
Thanks, I also found the [commit that added this](https://github.com/brendangregg/FlameGraph/commit/543c029f7ac195d1f8a3d4dd9fb14e122f9331fc) should be pretty straight forward to port over.

**Comment by rafiquemt** [comment]
Thanks for the quick turnaround!

**Comment by thlorenz** [comment]
Implemented a pan zoom (not 100% smooth yet, but more usable IMO than the subsection click way).
![flamegraph-zoom](https://cloud.githubusercontent.com/assets/192891/5762630/72a1e31a-9cb1-11e4-956b-db6e35900442.gif)

**Comment by rafiquemt** [comment]
Awesome!
